# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html

image: python:3.13-slim

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - pip install poetry
    - pip install streamlit
    - pip install matplotlib
    - pip install plotly
    - poetry config virtualenvs.create false
    - poetry install --no-dev
    - mkdir -p public
    - streamlit run streamlit/app.py --server.port=8501 --server.headless=true &
    - sleep 5  # Allow Streamlit to start
    - curl http://localhost:8501 > public/index.html
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
